export const procedures = [
  {
    id: "limpeza-dental",
    name: "Limpeza Dental",
    category: "preventiva",
    price: 2000,
    duration: "45 min",
    description:
      "Limpeza profissional completa para manter a saúde bucal em dia. Remove tártaro, placa bacteriana e manchas superficiais, deixando os dentes limpos e saudáveis.",
    image: "/placeholder.svg?height=300&width=400",
    benefits: [
      "Remove tártaro e placa bacteriana",
      "Previne doenças gengivais",
      "Deixa os dentes mais brancos",
      "Hálito mais fresco",
      "Detecção precoce de problemas",
    ],
  },
  {
    id: "clareamento-dental",
    name: "Clareamento Dental",
    category: "estetica",
    price: 5000,
    duration: "1h 30min",
    description:
      "Tratamento estético avançado para clarear os dentes de forma segura e eficaz. Utilizamos tecnologia LED para resultados superiores e duradouros.",
    image: "/placeholder.svg?height=300&width=400",
    benefits: [
      "Dentes até 8 tons mais brancos",
      "Procedimento seguro e indolor",
      "Resultados imediatos",
      "Tecnologia LED avançada",
      "Aumento da autoestima",
    ],
  },
  {
    id: "implantes-dentarios",
    name: "Implantes Dentários",
    category: "cirurgia",
    price: 15000,
    duration: "2h",
    description:
      "Substituição de dentes perdidos com implantes de titânio de alta qualidade. Solução permanente e natural para recuperar o sorriso e a função mastigatória.",
    image: "/placeholder.svg?height=300&width=400",
    benefits: [
      "Solução permanente",
      "Aparência natural",
      "Preserva o osso maxilar",
      "Não afeta dentes adjacentes",
      "Alta taxa de sucesso",
    ],
  },
  {
    id: "ortodontia",
    name: "Ortodontia",
    category: "ortodontia",
    price: 12000,
    duration: "45 min",
    description:
      "Correção do alinhamento dos dentes com aparelhos modernos. Oferecemos opções tradicionais e estéticas para todas as idades.",
    image: "/placeholder.svg?height=300&width=400",
    benefits: [
      "Dentes perfeitamente alinhados",
      "Melhora da mastigação",
      "Facilita a higienização",
      "Aumenta a autoconfiança",
      "Opções estéticas disponíveis",
    ],
  },
  {
    id: "facetas-porcelana",
    name: "Facetas de Porcelana",
    category: "estetica",
    price: 8000,
    duration: "2h",
    description:
      "Lâminas ultrafinas de porcelana aplicadas sobre os dentes para corrigir imperfeições e criar um sorriso perfeito.",
    image: "/placeholder.svg?height=300&width=400",
    benefits: [
      "Sorriso perfeito instantâneo",
      "Corrige múltiplas imperfeições",
      "Material resistente e durável",
      "Aparência natural",
      "Mínimo desgaste dental",
    ],
  },
  {
    id: "canal-radicular",
    name: "Tratamento de Canal",
    category: "cirurgia",
    price: 6000,
    duration: "1h 30min",
    description:
      "Tratamento endodôntico para salvar dentes com polpa infectada ou danificada. Procedimento indolor com tecnologia rotativa.",
    image: "/placeholder.svg?height=300&width=400",
    benefits: [
      "Salva o dente natural",
      "Elimina a dor",
      "Procedimento indolor",
      "Tecnologia avançada",
      "Alta taxa de sucesso",
    ],
  },
  {
    id: "protese-dentaria",
    name: "Prótese Dentária",
    category: "cirurgia",
    price: 10000,
    duration: "1h",
    description:
      "Próteses fixas e removíveis personalizadas para substituir dentes perdidos. Materiais de alta qualidade para conforto e durabilidade.",
    image: "/placeholder.svg?height=300&width=400",
    benefits: [
      "Restaura a função mastigatória",
      "Melhora a fala",
      "Aparência natural",
      "Conforto garantido",
      "Materiais de qualidade",
    ],
  },
  {
    id: "cirurgia-siso",
    name: "Extração do Siso",
    category: "cirurgia",
    price: 4000,
    duration: "1h",
    description:
      "Remoção segura dos dentes do siso com técnicas minimamente invasivas. Pós-operatório confortável com acompanhamento completo.",
    image: "/placeholder.svg?height=300&width=400",
    benefits: [
      "Técnica minimamente invasiva",
      "Pós-operatório confortável",
      "Previne complicações futuras",
      "Acompanhamento completo",
      "Recuperação rápida",
    ],
  },
  {
    id: "periodontia",
    name: "Tratamento Periodontal",
    category: "preventiva",
    price: 3500,
    duration: "1h",
    description:
      "Tratamento especializado para doenças da gengiva e estruturas de suporte dos dentes. Previne a perda dentária e mantém a saúde bucal.",
    image: "/placeholder.svg?height=300&width=400",
    benefits: [
      "Trata doenças gengivais",
      "Previne perda dentária",
      "Melhora a saúde bucal",
      "Reduz inflamação",
      "Fortalece as gengivas",
    ],
  },
  {
    id: "odontopediatria",
    name: "Odontopediatria",
    category: "preventiva",
    price: 2500,
    duration: "30 min",
    description:
      "Cuidados dentários especializados para crianças em ambiente acolhedor e divertido. Criamos experiências positivas para os pequenos pacientes.",
    image: "/placeholder.svg?height=300&width=400",
    benefits: [
      "Ambiente acolhedor para crianças",
      "Profissionais especializados",
      "Prevenção desde cedo",
      "Experiência positiva",
      "Educação sobre higiene bucal",
    ],
  },
]
